version: "3"

networks:
   aplication:
      
services:

   nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
         - "8088:80"
      volumes:
         - ./backend:/var/www/html
         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

      depends_on: 
         - php
         - mysql
      networks: 
         - aplication
   
   mysql:
      image: mysql:5.7.22
      container_name: mysql
      restart: unless-stopped
      tty: true
      ports: 
         - "4306:3306"
      volumes: 
         - ./docker/mysql:/var/lib/mysql
      environment:
         MYSQL_DATABASE : homestead
         MYSQL_USER : homestead
         MYSQL_PASSWORD : 123456
         MYSQL_ROOT_PASSWORD : 123456
         SERVICE_NAME: mysql

      networks: 
         - aplication

   php:
      build: 
         context: ./backend
         dockerfile: Dockerfile      
      container_name: php
      ports: 
         - "9000:9000"
      volumes: 
         - ./backend:/var/www/html
      networks: 
         - aplication

   angular:
      build: 
         context: ./frontend
         dockerfile: Dockerfile      
      container_name: angular
      depends_on: 
         - php
      tty: true
      ports: 
         - "4200:4200"
      volumes: 
         - /app/node_modules
         - ./frontend:/app
      networks: 
         - aplication
      command: > 
         bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --poll 5000 "
      