<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
	/**
	* Seed the application's database.
	*
	* @return void
	*/
	public function run()
	{
		DB::table('departamentos')->insert(["id"=> "1",'nombre' => "Amazonas", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "2",'nombre' => "Antioquia", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "3",'nombre' => "Arauca", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "4",'nombre' => "Atlántico", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "5",'nombre' => "Bogotá", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "6",'nombre' => "Bolívar", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "7",'nombre' => "Boyacá", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "8",'nombre' => "Caldas", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "9",'nombre' => "Caquetá", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "10",'nombre' => "Casanare", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "11",'nombre' => "Cauca", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "12",'nombre' => "Cesar", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "13",'nombre' => "Chocó", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "14",'nombre' => "Córdoba", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "15",'nombre' => "Cundinamarca", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "16",'nombre' => "Guainía", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "17",'nombre' => "Guaviare", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "18",'nombre' => "Huila", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "19",'nombre' => "La Guajira", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "20",'nombre' => "Magdalena", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "21",'nombre' => "Meta", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "22",'nombre' => "Nariño", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "23",'nombre' => "Norte de Santander", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "24",'nombre' => "Putumayo", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "25",'nombre' => "Quindío", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "26",'nombre' => "Risaralda", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "27",'nombre' => "San Andrés y Providencia", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "28",'nombre' => "Santander", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "29",'nombre' => "Sucre", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "30",'nombre' => "Tolima", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "31",'nombre' => "Valle del Cauca", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "32",'nombre' => "Vaupés", "created_at" => now()]);
		DB::table('departamentos')->insert(["id"=> "33",'nombre' => "Vichada", "created_at" => now()]);
		
		
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Amazonas", 'departamento_id' => "1", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Amazonas", 'departamento_id' => "1", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Amazonas", 'departamento_id' => "1", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Amazonas", 'departamento_id' => "1", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Amazonas", 'departamento_id' => "1", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Antioquia", 'departamento_id' => "2", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Antioquia", 'departamento_id' => "2", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Antioquia", 'departamento_id' => "2", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Antioquia", 'departamento_id' => "2", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Antioquia", 'departamento_id' => "2", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Arauca", 'departamento_id' => "3", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Arauca", 'departamento_id' => "3", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Arauca", 'departamento_id' => "3", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Arauca", 'departamento_id' => "3", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Arauca", 'departamento_id' => "3", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Atlántico", 'departamento_id' => "4", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Atlántico", 'departamento_id' => "4", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Atlántico", 'departamento_id' => "4", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Atlántico", 'departamento_id' => "4", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Atlántico", 'departamento_id' => "4", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Bogotá", 'departamento_id' => "5", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Bogotá", 'departamento_id' => "5", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Bogotá", 'departamento_id' => "5", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Bogotá", 'departamento_id' => "5", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Bogotá", 'departamento_id' => "5", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Bolívar", 'departamento_id' => "6", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Bolívar", 'departamento_id' => "6", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Bolívar", 'departamento_id' => "6", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Bolívar", 'departamento_id' => "6", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Bolívar", 'departamento_id' => "6", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Boyacá", 'departamento_id' => "7", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Boyacá", 'departamento_id' => "7", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Boyacá", 'departamento_id' => "7", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Boyacá", 'departamento_id' => "7", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Boyacá", 'departamento_id' => "7", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Caldas", 'departamento_id' => "8", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Caldas", 'departamento_id' => "8", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Caldas", 'departamento_id' => "8", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Caldas", 'departamento_id' => "8", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Caldas", 'departamento_id' => "8", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Caquetá", 'departamento_id' => "9", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Caquetá", 'departamento_id' => "9", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Caquetá", 'departamento_id' => "9", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Caquetá", 'departamento_id' => "9", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Caquetá", 'departamento_id' => "9", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Casanare", 'departamento_id' => "10", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Casanare", 'departamento_id' => "10", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Casanare", 'departamento_id' => "10", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Casanare", 'departamento_id' => "10", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Casanare", 'departamento_id' => "10", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Cauca", 'departamento_id' => "11", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Cauca", 'departamento_id' => "11", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Cauca", 'departamento_id' => "11", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Cauca", 'departamento_id' => "11", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Cauca", 'departamento_id' => "11", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Cesar", 'departamento_id' => "12", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Cesar", 'departamento_id' => "12", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Cesar", 'departamento_id' => "12", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Cesar", 'departamento_id' => "12", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Cesar", 'departamento_id' => "12", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Chocó", 'departamento_id' => "13", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Chocó", 'departamento_id' => "13", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Chocó", 'departamento_id' => "13", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Chocó", 'departamento_id' => "13", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Chocó", 'departamento_id' => "13", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Córdoba", 'departamento_id' => "14", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Córdoba", 'departamento_id' => "14", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Córdoba", 'departamento_id' => "14", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Córdoba", 'departamento_id' => "14", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Córdoba", 'departamento_id' => "14", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Cundinamarca", 'departamento_id' => "15", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Cundinamarca", 'departamento_id' => "15", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Cundinamarca", 'departamento_id' => "15", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Cundinamarca", 'departamento_id' => "15", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Cundinamarca", 'departamento_id' => "15", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Guainía", 'departamento_id' => "16", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Guainía", 'departamento_id' => "16", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Guainía", 'departamento_id' => "16", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Guainía", 'departamento_id' => "16", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Guainía", 'departamento_id' => "16", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Guaviare", 'departamento_id' => "17", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Guaviare", 'departamento_id' => "17", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Guaviare", 'departamento_id' => "17", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Guaviare", 'departamento_id' => "17", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Guaviare", 'departamento_id' => "17", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Huila", 'departamento_id' => "18", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Huila", 'departamento_id' => "18", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Huila", 'departamento_id' => "18", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Huila", 'departamento_id' => "18", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Huila", 'departamento_id' => "18", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_La Guajira", 'departamento_id' => "19", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_La Guajira", 'departamento_id' => "19", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_La Guajira", 'departamento_id' => "19", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_La Guajira", 'departamento_id' => "19", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_La Guajira", 'departamento_id' => "19", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Magdalena", 'departamento_id' => "20", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Magdalena", 'departamento_id' => "20", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Magdalena", 'departamento_id' => "20", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Magdalena", 'departamento_id' => "20", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Magdalena", 'departamento_id' => "20", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Meta", 'departamento_id' => "21", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Meta", 'departamento_id' => "21", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Meta", 'departamento_id' => "21", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Meta", 'departamento_id' => "21", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Meta", 'departamento_id' => "21", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Nariño", 'departamento_id' => "22", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Nariño", 'departamento_id' => "22", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Nariño", 'departamento_id' => "22", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Nariño", 'departamento_id' => "22", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Nariño", 'departamento_id' => "22", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Norte de Santander", 'departamento_id' => "23", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Norte de Santander", 'departamento_id' => "23", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Norte de Santander", 'departamento_id' => "23", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Norte de Santander", 'departamento_id' => "23", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Norte de Santander", 'departamento_id' => "23", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Putumayo", 'departamento_id' => "24", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Putumayo", 'departamento_id' => "24", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Putumayo", 'departamento_id' => "24", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Putumayo", 'departamento_id' => "24", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Putumayo", 'departamento_id' => "24", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Quindío", 'departamento_id' => "25", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Quindío", 'departamento_id' => "25", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Quindío", 'departamento_id' => "25", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Quindío", 'departamento_id' => "25", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Quindío", 'departamento_id' => "25", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Risaralda", 'departamento_id' => "26", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Risaralda", 'departamento_id' => "26", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Risaralda", 'departamento_id' => "26", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Risaralda", 'departamento_id' => "26", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Risaralda", 'departamento_id' => "26", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_San Andrés y Providencia", 'departamento_id' => "27", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_San Andrés y Providencia", 'departamento_id' => "27", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_San Andrés y Providencia", 'departamento_id' => "27", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_San Andrés y Providencia", 'departamento_id' => "27", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_San Andrés y Providencia", 'departamento_id' => "27", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Santander", 'departamento_id' => "28", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Santander", 'departamento_id' => "28", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Santander", 'departamento_id' => "28", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Santander", 'departamento_id' => "28", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Santander", 'departamento_id' => "28", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Sucre", 'departamento_id' => "29", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Sucre", 'departamento_id' => "29", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Sucre", 'departamento_id' => "29", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Sucre", 'departamento_id' => "29", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Sucre", 'departamento_id' => "29", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Tolima", 'departamento_id' => "30", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Tolima", 'departamento_id' => "30", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Tolima", 'departamento_id' => "30", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Tolima", 'departamento_id' => "30", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Tolima", 'departamento_id' => "30", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Valle del Cauca", 'departamento_id' => "31", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Valle del Cauca", 'departamento_id' => "31", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Valle del Cauca", 'departamento_id' => "31", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Valle del Cauca", 'departamento_id' => "31", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Valle del Cauca", 'departamento_id' => "31", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Vaupés", 'departamento_id' => "32", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Vaupés", 'departamento_id' => "32", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Vaupés", 'departamento_id' => "32", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Vaupés", 'departamento_id' => "32", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Vaupés", 'departamento_id' => "32", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 1_Vichada", 'departamento_id' => "33", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 2_Vichada", 'departamento_id' => "33", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 3_Vichada", 'departamento_id' => "33", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 4_Vichada", 'departamento_id' => "33", "created_at" => now()]);
		DB::table('municipios')->insert(['nombre' => "Municipio 5_Vichada", 'departamento_id' => "33", "created_at" => now()]);
		
	}
}
